spring.data.mongodb.host=localhost
spring.data.redis.host=localhost

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

jwt.secret=jwt_secret_key_123_jwt_secret_key_123
inventory.service.url=http://localhost:8083
