spring.data.mongodb.host=cart-mongodb
spring.data.redis.host=cart-redis

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
