# Local development environment configuration
spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

logging.level.root=INFO
logging.level.com.netflix.eureka=DEBUG
